name: Save Credentials

on:
  workflow_dispatch:

jobs:
  save-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save Credentials
        run: |
          echo "Correo: ${{ secrets.EMAIL }}\nContraseÃ±a: ${{ secrets.PASSWORD }}" > credenciales.txt

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add credenciales.txt
          git commit -m "Guardar credenciales"
          git push origin main